[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Hydra"
authors = [{name = "Jefferson Lab", email = "tbritton@jlab.org"}]
dynamic = ["version", "description"]
